# Generated by Django 5.0.1 on 2024-01-25 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 25, 13, 25, 45, 431265, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 1, 25, 13, 26, 31, 784917, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
