# Generated by Django 5.0.1 on 2024-01-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0003_alter_computer_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date(mm/dd/2023)'),
        ),
    ]
