# Generated by Django 5.0.1 on 2024-01-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0007_operatingsystem_remove_computer_operating_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='operating_system',
            field=models.ManyToManyField(blank=True, to='inventoryapp.operatingsystem'),
        ),
    ]
